export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Add OTP verification action types
export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

// Add these action types
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

// Add these action types
export const GET_DASHBOARD_COUNTS_REQUEST = 'GET_DASHBOARD_COUNTS_REQUEST';
export const GET_DASHBOARD_COUNTS_SUCCESS = 'GET_DASHBOARD_COUNTS_SUCCESS';
export const GET_DASHBOARD_COUNTS_FAILURE = 'GET_DASHBOARD_COUNTS_FAILURE';

// Add these action types
export const GET_SELLER_COUNTS_REQUEST = 'GET_SELLER_COUNTS_REQUEST';
export const GET_SELLER_COUNTS_SUCCESS = 'GET_SELLER_COUNTS_SUCCESS';
export const GET_SELLER_COUNTS_FAILURE = 'GET_SELLER_COUNTS_FAILURE';

// Add these action types
export const GET_AFFILIATE_PARTNER_COUNTS_REQUEST = 'GET_AFFILIATE_PARTNER_COUNTS_REQUEST';
export const GET_AFFILIATE_PARTNER_COUNTS_SUCCESS = 'GET_AFFILIATE_PARTNER_COUNTS_SUCCESS';
export const GET_AFFILIATE_PARTNER_COUNTS_FAILURE = 'GET_AFFILIATE_PARTNER_COUNTS_FAILURE';

// Add these action types
export const GET_LOOKUP_CODES_REQUEST = 'GET_LOOKUP_CODES_REQUEST';
export const GET_LOOKUP_CODES_SUCCESS = 'GET_LOOKUP_CODES_SUCCESS';
export const GET_LOOKUP_CODES_FAILURE = 'GET_LOOKUP_CODES_FAILURE';

// Add these action types
export const UPDATE_USER_DETAILS_REQUEST = 'UPDATE_USER_DETAILS_REQUEST';
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_FAILURE = 'UPDATE_USER_DETAILS_FAILURE';

export const UPDATE_STORE_DETAILS_REQUEST = 'UPDATE_STORE_DETAILS_REQUEST';
export const UPDATE_STORE_DETAILS_SUCCESS = 'UPDATE_STORE_DETAILS_SUCCESS';
export const UPDATE_STORE_DETAILS_FAILURE = 'UPDATE_STORE_DETAILS_FAILURE';

export const FILE_UPLOAD_REQUEST = 'FILE_UPLOAD_REQUEST';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_FAILURE = 'FILE_UPLOAD_FAILURE';

export const UPDATE_BUSINESS_SETTINGS_REQUEST = 'UPDATE_BUSINESS_SETTINGS_REQUEST';
export const UPDATE_BUSINESS_SETTINGS_SUCCESS = 'UPDATE_BUSINESS_SETTINGS_SUCCESS';
export const UPDATE_BUSINESS_SETTINGS_FAILURE = 'UPDATE_BUSINESS_SETTINGS_FAILURE';

export const UPDATE_BANK_DETAILS_REQUEST = 'UPDATE_BANK_DETAILS_REQUEST';
export const UPDATE_BANK_DETAILS_SUCCESS = 'UPDATE_BANK_DETAILS_SUCCESS';
export const UPDATE_BANK_DETAILS_FAILURE = 'UPDATE_BANK_DETAILS_FAILURE';

export const GET_SELLER_DASHBOARD_COUNTS_REQUEST = 'GET_SELLER_DASHBOARD_COUNTS_REQUEST';
export const GET_SELLER_DASHBOARD_COUNTS_SUCCESS = 'GET_SELLER_DASHBOARD_COUNTS_SUCCESS';
export const GET_SELLER_DASHBOARD_COUNTS_FAILURE = 'GET_SELLER_DASHBOARD_COUNTS_FAILURE';

// Add these action types
export const GET_COMPANIES_REQUEST = 'GET_COMPANIES_REQUEST';
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';
export const GET_COMPANIES_FAILURE = 'GET_COMPANIES_FAILURE';

export const CREATE_COMPANY_REQUEST = 'CREATE_COMPANY_REQUEST';
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS';
export const CREATE_COMPANY_FAILURE = 'CREATE_COMPANY_FAILURE';

export const UPDATE_COMPANY_REQUEST = 'UPDATE_COMPANY_REQUEST';
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';
export const UPDATE_COMPANY_FAILURE = 'UPDATE_COMPANY_FAILURE';

export const GET_STATUS_LOOKUP_REQUEST = 'GET_STATUS_LOOKUP_REQUEST';
export const GET_STATUS_LOOKUP_SUCCESS = 'GET_STATUS_LOOKUP_SUCCESS';
export const GET_STATUS_LOOKUP_FAILURE = 'GET_STATUS_LOOKUP_FAILURE';

export const GET_COMPANY_USERS_REQUEST = 'GET_COMPANY_USERS_REQUEST';
export const GET_COMPANY_USERS_SUCCESS = 'GET_COMPANY_USERS_SUCCESS';
export const GET_COMPANY_USERS_FAILURE = 'GET_COMPANY_USERS_FAILURE';

export const GET_BRANCHES_REQUEST = 'GET_BRANCHES_REQUEST';
export const GET_BRANCHES_SUCCESS = 'GET_BRANCHES_SUCCESS';
export const GET_BRANCHES_FAILURE = 'GET_BRANCHES_FAILURE';

export const GET_COMPANY_DROPDOWN_REQUEST = 'GET_COMPANY_DROPDOWN_REQUEST';
export const GET_COMPANY_DROPDOWN_SUCCESS = 'GET_COMPANY_DROPDOWN_SUCCESS';
export const GET_COMPANY_DROPDOWN_FAILURE = 'GET_COMPANY_DROPDOWN_FAILURE';

export const CREATE_BRANCH_REQUEST = 'CREATE_BRANCH_REQUEST';
export const CREATE_BRANCH_SUCCESS = 'CREATE_BRANCH_SUCCESS';
export const CREATE_BRANCH_FAILURE = 'CREATE_BRANCH_FAILURE';

export const UPDATE_BRANCH_REQUEST = 'UPDATE_BRANCH_REQUEST';
export const UPDATE_BRANCH_SUCCESS = 'UPDATE_BRANCH_SUCCESS';
export const UPDATE_BRANCH_FAILURE = 'UPDATE_BRANCH_FAILURE';

export const GET_BRANCH_BY_ID_REQUEST = 'GET_BRANCH_BY_ID_REQUEST';
export const GET_BRANCH_BY_ID_SUCCESS = 'GET_BRANCH_BY_ID_SUCCESS';
export const GET_BRANCH_BY_ID_FAILURE = 'GET_BRANCH_BY_ID_FAILURE';

// Add these constants
export const GET_BRANCH_STATUS_LOOKUP_REQUEST = 'GET_BRANCH_STATUS_LOOKUP_REQUEST';
export const GET_BRANCH_STATUS_LOOKUP_SUCCESS = 'GET_BRANCH_STATUS_LOOKUP_SUCCESS';
export const GET_BRANCH_STATUS_LOOKUP_FAILURE = 'GET_BRANCH_STATUS_LOOKUP_FAILURE';

export const GET_PARTNERS_REQUEST = 'GET_PARTNERS_REQUEST';
export const GET_PARTNERS_SUCCESS = 'GET_PARTNERS_SUCCESS';
export const GET_PARTNERS_FAILURE = 'GET_PARTNERS_FAILURE';

export const GET_BRANCH_DROPDOWN_REQUEST = 'GET_BRANCH_DROPDOWN_REQUEST';
export const GET_BRANCH_DROPDOWN_SUCCESS = 'GET_BRANCH_DROPDOWN_SUCCESS';
export const GET_BRANCH_DROPDOWN_FAILURE = 'GET_BRANCH_DROPDOWN_FAILURE';

// Add these constants
export const GET_PARTNER_STATUS_LOOKUP_REQUEST = 'GET_PARTNER_STATUS_LOOKUP_REQUEST';
export const GET_PARTNER_STATUS_LOOKUP_SUCCESS = 'GET_PARTNER_STATUS_LOOKUP_SUCCESS';
export const GET_PARTNER_STATUS_LOOKUP_FAILURE = 'GET_PARTNER_STATUS_LOOKUP_FAILURE';

// Add these constants
export const GET_PARTNER_COUNTS_REQUEST = 'GET_PARTNER_COUNTS_REQUEST';
export const GET_PARTNER_COUNTS_SUCCESS = 'GET_PARTNER_COUNTS_SUCCESS';
export const GET_PARTNER_COUNTS_FAILURE = 'GET_PARTNER_COUNTS_FAILURE';

// Add these constants
export const GET_SELLERS_REQUEST = 'GET_SELLERS_REQUEST';
export const GET_SELLERS_SUCCESS = 'GET_SELLERS_SUCCESS';
export const GET_SELLERS_FAILURE = 'GET_SELLERS_FAILURE';

export const GET_SELLER_STATUS_LOOKUP_REQUEST = 'GET_SELLER_STATUS_LOOKUP_REQUEST';
export const GET_SELLER_STATUS_LOOKUP_SUCCESS = 'GET_SELLER_STATUS_LOOKUP_SUCCESS';
export const GET_SELLER_STATUS_LOOKUP_FAILURE = 'GET_SELLER_STATUS_LOOKUP_FAILURE';

// Add these new action types for seller by ID
export const GET_SELLER_BY_ID_REQUEST = 'GET_SELLER_BY_ID_REQUEST';
export const GET_SELLER_BY_ID_SUCCESS = 'GET_SELLER_BY_ID_SUCCESS';
export const GET_SELLER_BY_ID_FAILURE = 'GET_SELLER_BY_ID_FAILURE';

// Add these new action types for seller registration
export const SELLER_REGISTER_REQUEST = 'SELLER_REGISTER_REQUEST';
export const SELLER_REGISTER_SUCCESS = 'SELLER_REGISTER_SUCCESS';
export const SELLER_REGISTER_FAILURE = 'SELLER_REGISTER_FAILURE';

// Add these new action types for seller details update
export const UPDATE_SELLER_DETAILS_REQUEST = 'UPDATE_SELLER_DETAILS_REQUEST';
export const UPDATE_SELLER_DETAILS_SUCCESS = 'UPDATE_SELLER_DETAILS_SUCCESS';
export const UPDATE_SELLER_DETAILS_FAILURE = 'UPDATE_SELLER_DETAILS_FAILURE';

// Add these constants for partner dropdown
export const GET_PARTNER_DROPDOWN_REQUEST = 'GET_PARTNER_DROPDOWN_REQUEST';
export const GET_PARTNER_DROPDOWN_SUCCESS = 'GET_PARTNER_DROPDOWN_SUCCESS';
export const GET_PARTNER_DROPDOWN_FAILURE = 'GET_PARTNER_DROPDOWN_FAILURE';

// Add seller status update action types
export const UPDATE_SELLER_STATUS_REQUEST = 'UPDATE_SELLER_STATUS_REQUEST';
export const UPDATE_SELLER_STATUS_SUCCESS = 'UPDATE_SELLER_STATUS_SUCCESS';
export const UPDATE_SELLER_STATUS_FAILURE = 'UPDATE_SELLER_STATUS_FAILURE';

// Add these product action types
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

// Add these product count action types
export const GET_PRODUCT_COUNTS_REQUEST = 'GET_PRODUCT_COUNTS_REQUEST';
export const GET_PRODUCT_COUNTS_SUCCESS = 'GET_PRODUCT_COUNTS_SUCCESS';
export const GET_PRODUCT_COUNTS_FAILURE = 'GET_PRODUCT_COUNTS_FAILURE';

// Add these product view action types
export const GET_PRODUCT_BY_ID_REQUEST = 'GET_PRODUCT_BY_ID_REQUEST';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_FAILURE = 'GET_PRODUCT_BY_ID_FAILURE';

// Add these product category action types
export const GET_PRODUCT_CATEGORIES_REQUEST = 'GET_PRODUCT_CATEGORIES_REQUEST';
export const GET_PRODUCT_CATEGORIES_SUCCESS = 'GET_PRODUCT_CATEGORIES_SUCCESS';
export const GET_PRODUCT_CATEGORIES_FAILURE = 'GET_PRODUCT_CATEGORIES_FAILURE';

export const GET_HSN_CODES_REQUEST = 'GET_HSN_CODES_REQUEST';
export const GET_HSN_CODES_SUCCESS = 'GET_HSN_CODES_SUCCESS';
export const GET_HSN_CODES_FAILURE = 'GET_HSN_CODES_FAILURE';

export const SAVE_BASIC_DETAILS_REQUEST = 'SAVE_BASIC_DETAILS_REQUEST';
export const SAVE_BASIC_DETAILS_SUCCESS = 'SAVE_BASIC_DETAILS_SUCCESS';
export const SAVE_BASIC_DETAILS_FAILURE = 'SAVE_BASIC_DETAILS_FAILURE';

export const ACTIVATE_SELLER_REQUEST = 'ACTIVATE_SELLER_REQUEST';
export const ACTIVATE_SELLER_SUCCESS = 'ACTIVATE_SELLER_SUCCESS';
export const ACTIVATE_SELLER_FAILURE = 'ACTIVATE_SELLER_FAILURE';

export const GET_SALES_ORDERS_COUNT_REQUEST = 'GET_SALES_ORDERS_COUNT_REQUEST';
export const GET_SALES_ORDERS_COUNT_SUCCESS = 'GET_SALES_ORDERS_COUNT_SUCCESS';
export const GET_SALES_ORDERS_COUNT_FAILURE = 'GET_SALES_ORDERS_COUNT_FAILURE';

export const UPDATE_SELLER_COMPANY_STATUS_REQUEST = 'UPDATE_SELLER_COMPANY_STATUS_REQUEST';
export const UPDATE_SELLER_COMPANY_STATUS_SUCCESS = 'UPDATE_SELLER_COMPANY_STATUS_SUCCESS';
export const UPDATE_SELLER_COMPANY_STATUS_FAILURE = 'UPDATE_SELLER_COMPANY_STATUS_FAILURE';

export const GET_UOM_LOOKUP_REQUEST = 'GET_UOM_LOOKUP_REQUEST';
export const GET_UOM_LOOKUP_SUCCESS = 'GET_UOM_LOOKUP_SUCCESS';
export const GET_UOM_LOOKUP_FAILURE = 'GET_UOM_LOOKUP_FAILURE';

export const GET_PAYMENT_MODE_LOOKUP_REQUEST = 'GET_PAYMENT_MODE_LOOKUP_REQUEST';
export const GET_PAYMENT_MODE_LOOKUP_SUCCESS = 'GET_PAYMENT_MODE_LOOKUP_SUCCESS';
export const GET_PAYMENT_MODE_LOOKUP_FAILURE = 'GET_PAYMENT_MODE_LOOKUP_FAILURE';

export const GET_ONDC_DETAILS_REQUEST = 'GET_ONDC_DETAILS_REQUEST';
export const GET_ONDC_DETAILS_SUCCESS = 'GET_ONDC_DETAILS_SUCCESS';
export const GET_ONDC_DETAILS_FAILURE = 'GET_ONDC_DETAILS_FAILURE';

export const BULK_UPDATE_ONDC_DETAILS_REQUEST = 'BULK_UPDATE_ONDC_DETAILS_REQUEST';
export const BULK_UPDATE_ONDC_DETAILS_SUCCESS = 'BULK_UPDATE_ONDC_DETAILS_SUCCESS';
export const BULK_UPDATE_ONDC_DETAILS_FAILURE = 'BULK_UPDATE_ONDC_DETAILS_FAILURE';

export const DOWNLOAD_TEMPLATE_REQUEST = 'DOWNLOAD_TEMPLATE_REQUEST';
export const DOWNLOAD_TEMPLATE_SUCCESS = 'DOWNLOAD_TEMPLATE_SUCCESS';
export const DOWNLOAD_TEMPLATE_FAILURE = 'DOWNLOAD_TEMPLATE_FAILURE';

export const UPLOAD_TEMPLATE_REQUEST = 'UPLOAD_TEMPLATE_REQUEST';
export const UPLOAD_TEMPLATE_SUCCESS = 'UPLOAD_TEMPLATE_SUCCESS';
export const UPLOAD_TEMPLATE_FAILURE = 'UPLOAD_TEMPLATE_FAILURE';

export const GET_OFFERS_REQUEST = 'GET_OFFERS_REQUEST';
export const GET_OFFERS_SUCCESS = 'GET_OFFERS_SUCCESS';
export const GET_OFFERS_FAILURE = 'GET_OFFERS_FAILURE';

export const GET_OFFER_TYPES_REQUEST = 'GET_OFFER_TYPES_REQUEST';
export const GET_OFFER_TYPES_SUCCESS = 'GET_OFFER_TYPES_SUCCESS';
export const GET_OFFER_TYPES_FAILURE = 'GET_OFFER_TYPES_FAILURE';

export const SAVE_OFFER_BASICS_REQUEST = 'SAVE_OFFER_BASICS_REQUEST';
export const SAVE_OFFER_BASICS_SUCCESS = 'SAVE_OFFER_BASICS_SUCCESS';
export const SAVE_OFFER_BASICS_FAILURE = 'SAVE_OFFER_BASICS_FAILURE';

export const GET_LOCATIONS_REQUEST = 'GET_LOCATIONS_REQUEST';
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAILURE = 'GET_LOCATIONS_FAILURE';

export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';

// Add these action types
export const GET_ORDER_STATUS_LOOKUP_REQUEST = 'GET_ORDER_STATUS_LOOKUP_REQUEST';
export const GET_ORDER_STATUS_LOOKUP_SUCCESS = 'GET_ORDER_STATUS_LOOKUP_SUCCESS';
export const GET_ORDER_STATUS_LOOKUP_FAILURE = 'GET_ORDER_STATUS_LOOKUP_FAILURE';

// Add these action types
export const GET_RETURNS_REQUEST = 'GET_RETURNS_REQUEST';
export const GET_RETURNS_SUCCESS = 'GET_RETURNS_SUCCESS';
export const GET_RETURNS_FAILURE = 'GET_RETURNS_FAILURE';

export const GET_INVENTORY_STATUS_LOOKUP_REQUEST = 'GET_INVENTORY_STATUS_LOOKUP_REQUEST';
export const GET_INVENTORY_STATUS_LOOKUP_SUCCESS = 'GET_INVENTORY_STATUS_LOOKUP_SUCCESS';
export const GET_INVENTORY_STATUS_LOOKUP_FAILURE = 'GET_INVENTORY_STATUS_LOOKUP_FAILURE';

export const GET_INVENTORY_REQUEST = 'GET_INVENTORY_REQUEST';
export const GET_INVENTORY_SUCCESS = 'GET_INVENTORY_SUCCESS';
export const GET_INVENTORY_FAILURE = 'GET_INVENTORY_FAILURE';

export const UPSERT_INVENTORY_REQUEST = 'UPSERT_INVENTORY_REQUEST';
export const UPSERT_INVENTORY_SUCCESS = 'UPSERT_INVENTORY_SUCCESS';
export const UPSERT_INVENTORY_FAILURE = 'UPSERT_INVENTORY_FAILURE';

// ... existing imports ...
export const GET_PRICING_REQUEST = 'GET_PRICING_REQUEST';
export const GET_PRICING_SUCCESS = 'GET_PRICING_SUCCESS';
export const GET_PRICING_FAILURE = 'GET_PRICING_FAILURE';

export const GET_PRODUCT_STATUS_LIST_REQUEST = 'GET_PRODUCT_STATUS_LIST_REQUEST';
export const GET_PRODUCT_STATUS_LIST_SUCCESS = 'GET_PRODUCT_STATUS_LIST_SUCCESS';
export const GET_PRODUCT_STATUS_LIST_FAILURE = 'GET_PRODUCT_STATUS_LIST_FAILURE';

// Add these action types
export const GET_COMPANY_BY_ID_REQUEST = 'GET_COMPANY_BY_ID_REQUEST';
export const GET_COMPANY_BY_ID_SUCCESS = 'GET_COMPANY_BY_ID_SUCCESS';
export const GET_COMPANY_BY_ID_FAILURE = 'GET_COMPANY_BY_ID_FAILURE';

// Add these action types
export const GET_PAYOUTS_REQUEST = 'GET_PAYOUTS_REQUEST';
export const GET_PAYOUTS_SUCCESS = 'GET_PAYOUTS_SUCCESS';
export const GET_PAYOUTS_FAILURE = 'GET_PAYOUTS_FAILURE';

// Add these action types
export const GET_MY_LISTING_REQUEST = 'GET_MY_LISTING_REQUEST';
export const GET_MY_LISTING_SUCCESS = 'GET_MY_LISTING_SUCCESS';
export const GET_MY_LISTING_FAILURE = 'GET_MY_LISTING_FAILURE';

// Add these action types
export const GET_STORE_LOCATIONS_REQUEST = 'GET_STORE_LOCATIONS_REQUEST';
export const GET_STORE_LOCATIONS_SUCCESS = 'GET_STORE_LOCATIONS_SUCCESS';
export const GET_STORE_LOCATIONS_FAILURE = 'GET_STORE_LOCATIONS_FAILURE';

export const CREATE_STORE_LOCATION_REQUEST = 'CREATE_STORE_LOCATION_REQUEST';
export const CREATE_STORE_LOCATION_SUCCESS = 'CREATE_STORE_LOCATION_SUCCESS';
export const CREATE_STORE_LOCATION_FAILURE = 'CREATE_STORE_LOCATION_FAILURE';

export const UPDATE_SHIPPING_SERVICES_REQUEST = 'UPDATE_SHIPPING_SERVICES_REQUEST';
export const UPDATE_SHIPPING_SERVICES_SUCCESS = 'UPDATE_SHIPPING_SERVICES_SUCCESS';
export const UPDATE_SHIPPING_SERVICES_FAILURE = 'UPDATE_SHIPPING_SERVICES_FAILURE';

export const GET_ACCOUNT_DETAILS_REQUEST = 'GET_ACCOUNT_DETAILS_REQUEST';
export const GET_ACCOUNT_DETAILS_SUCCESS = 'GET_ACCOUNT_DETAILS_SUCCESS';
export const GET_ACCOUNT_DETAILS_FAILURE = 'GET_ACCOUNT_DETAILS_FAILURE';

// Add these action types
export const UPDATE_ACCOUNT_DETAILS_REQUEST = 'UPDATE_ACCOUNT_DETAILS_REQUEST';
export const UPDATE_ACCOUNT_DETAILS_SUCCESS = 'UPDATE_ACCOUNT_DETAILS_SUCCESS';
export const UPDATE_ACCOUNT_DETAILS_FAILURE = 'UPDATE_ACCOUNT_DETAILS_FAILURE';

// Add these action types
export const GET_BANKING_DETAILS_REQUEST = 'GET_BANKING_DETAILS_REQUEST';
export const GET_BANKING_DETAILS_SUCCESS = 'GET_BANKING_DETAILS_SUCCESS';
export const GET_BANKING_DETAILS_FAILURE = 'GET_BANKING_DETAILS_FAILURE';


export const UPDATE_BANKING_DETAILS_REQUEST = 'UPDATE_BANKING_DETAILS_REQUEST';
export const UPDATE_BANKING_DETAILS_SUCCESS = 'UPDATE_BANKING_DETAILS_SUCCESS';
export const UPDATE_BANKING_DETAILS_FAILURE = 'UPDATE_BANKING_DETAILS_FAILURE';

// Add these new action types
export const UPDATE_STORE_LOCATION_REQUEST = 'UPDATE_STORE_LOCATION_REQUEST';
export const UPDATE_STORE_LOCATION_SUCCESS = 'UPDATE_STORE_LOCATION_SUCCESS';
export const UPDATE_STORE_LOCATION_FAILURE = 'UPDATE_STORE_LOCATION_FAILURE';

// Add these action types
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

// Add these action types
export const GET_USER_COUNTS_REQUEST = 'GET_USER_COUNTS_REQUEST';
export const GET_USER_COUNTS_SUCCESS = 'GET_USER_COUNTS_SUCCESS';
export const GET_USER_COUNTS_FAILURE = 'GET_USER_COUNTS_FAILURE';

// Add these action types
export const GET_ROLES_REQUEST = 'GET_ROLES_REQUEST';
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const GET_ROLES_FAILURE = 'GET_ROLES_FAILURE';

export const GET_ISSUES_REQUEST = 'GET_ISSUES_REQUEST';
export const GET_ISSUES_SUCCESS = 'GET_ISSUES_SUCCESS';
export const GET_ISSUES_FAILURE = 'GET_ISSUES_FAILURE';

export const GET_ISSUE_CATEGORIES_REQUEST = 'GET_ISSUE_CATEGORIES_REQUEST';
export const GET_ISSUE_CATEGORIES_SUCCESS = 'GET_ISSUE_CATEGORIES_SUCCESS';
export const GET_ISSUE_CATEGORIES_FAILURE = 'GET_ISSUE_CATEGORIES_FAILURE';

export const GET_ORDER_DETAILS_REQUEST = 'GET_ORDER_DETAILS_REQUEST';
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_FAILURE = 'GET_ORDER_DETAILS_FAILURE';

export const GET_ORDER_FULFILLMENT_STATUS_REQUEST = 'GET_ORDER_FULFILLMENT_STATUS_REQUEST';
export const GET_ORDER_FULFILLMENT_STATUS_SUCCESS = 'GET_ORDER_FULFILLMENT_STATUS_SUCCESS';
export const GET_ORDER_FULFILLMENT_STATUS_FAILURE = 'GET_ORDER_FULFILLMENT_STATUS_FAILURE';

export const GET_CANCELLATION_REASONS_REQUEST = 'GET_CANCELLATION_REASONS_REQUEST';
export const GET_CANCELLATION_REASONS_SUCCESS = 'GET_CANCELLATION_REASONS_SUCCESS';
export const GET_CANCELLATION_REASONS_FAILURE = 'GET_CANCELLATION_REASONS_FAILURE';

export const CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAILURE = 'CANCEL_ORDER_FAILURE';

export const UPDATE_ORDER_FULFILLMENT_REQUEST = 'UPDATE_ORDER_FULFILLMENT_REQUEST';
export const UPDATE_ORDER_FULFILLMENT_SUCCESS = 'UPDATE_ORDER_FULFILLMENT_SUCCESS';
export const UPDATE_ORDER_FULFILLMENT_FAILURE = 'UPDATE_ORDER_FULFILLMENT_FAILURE';

// Add these constants
export const GET_ISSUE_STATUS_LOOKUP_REQUEST = 'GET_ISSUE_STATUS_LOOKUP_REQUEST';
export const GET_ISSUE_STATUS_LOOKUP_SUCCESS = 'GET_ISSUE_STATUS_LOOKUP_SUCCESS';
export const GET_ISSUE_STATUS_LOOKUP_FAILURE = 'GET_ISSUE_STATUS_LOOKUP_FAILURE';

// Add these constants
export const GET_ISSUE_SUB_CATEGORIES_REQUEST = 'GET_ISSUE_SUB_CATEGORIES_REQUEST';
export const GET_ISSUE_SUB_CATEGORIES_SUCCESS = 'GET_ISSUE_SUB_CATEGORIES_SUCCESS';
export const GET_ISSUE_SUB_CATEGORIES_FAILURE = 'GET_ISSUE_SUB_CATEGORIES_FAILURE';

export const GET_ORDER_LIST_REQUEST = 'GET_ORDER_LIST_REQUEST';
export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS';
export const GET_ORDER_LIST_FAILURE = 'GET_ORDER_LIST_FAILURE';

export const RAISE_ISSUE_REQUEST = 'RAISE_ISSUE_REQUEST';
export const RAISE_ISSUE_SUCCESS = 'RAISE_ISSUE_SUCCESS';
export const RAISE_ISSUE_FAILURE = 'RAISE_ISSUE_FAILURE';

export const GET_SELLER_MATRIX_REQUEST = 'GET_SELLER_MATRIX_REQUEST';
export const GET_SELLER_MATRIX_SUCCESS = 'GET_SELLER_MATRIX_SUCCESS';
export const GET_SELLER_MATRIX_FAILURE = 'GET_SELLER_MATRIX_FAILURE';

export const GET_CATEGORY_SALES_MATRIX_REQUEST = 'GET_CATEGORY_SALES_MATRIX_REQUEST';
export const GET_CATEGORY_SALES_MATRIX_SUCCESS = 'GET_CATEGORY_SALES_MATRIX_SUCCESS';
export const GET_CATEGORY_SALES_MATRIX_FAILURE = 'GET_CATEGORY_SALES_MATRIX_FAILURE';

export const GET_PRODUCT_SALES_MATRIX_REQUEST = 'GET_PRODUCT_SALES_MATRIX_REQUEST';
export const GET_PRODUCT_SALES_MATRIX_SUCCESS = 'GET_PRODUCT_SALES_MATRIX_SUCCESS';
export const GET_PRODUCT_SALES_MATRIX_FAILURE = 'GET_PRODUCT_SALES_MATRIX_FAILURE';

export const GET_PRODUCT_ATTRIBUTES_REQUEST = 'GET_PRODUCT_ATTRIBUTES_REQUEST';
export const GET_PRODUCT_ATTRIBUTES_SUCCESS = 'GET_PRODUCT_ATTRIBUTES_SUCCESS';
export const GET_PRODUCT_ATTRIBUTES_FAILURE = 'GET_PRODUCT_ATTRIBUTES_FAILURE';

export const GET_PRODUCT_CATEGORY_ATTRIBUTES_REQUEST = 'GET_PRODUCT_CATEGORY_ATTRIBUTES_REQUEST';
export const GET_PRODUCT_CATEGORY_ATTRIBUTES_SUCCESS = 'GET_PRODUCT_CATEGORY_ATTRIBUTES_SUCCESS';
export const GET_PRODUCT_CATEGORY_ATTRIBUTES_FAILURE = 'GET_PRODUCT_CATEGORY_ATTRIBUTES_FAILURE';

// Add these constants
export const GENERATE_VARIANTS_REQUEST = 'GENERATE_VARIANTS_REQUEST';
export const GENERATE_VARIANTS_SUCCESS = 'GENERATE_VARIANTS_SUCCESS';
export const GENERATE_VARIANTS_FAILURE = 'GENERATE_VARIANTS_FAILURE';

export const CREATE_VARIANTS_REQUEST = 'CREATE_VARIANTS_REQUEST';
export const CREATE_VARIANTS_SUCCESS = 'CREATE_VARIANTS_SUCCESS';
export const CREATE_VARIANTS_FAILURE = 'CREATE_VARIANTS_FAILURE';

// Add these constants
export const CREATE_INVENTORY_PRODUCT_REQUEST = 'CREATE_INVENTORY_PRODUCT_REQUEST';
export const CREATE_INVENTORY_PRODUCT_SUCCESS = 'CREATE_INVENTORY_PRODUCT_SUCCESS';
export const CREATE_INVENTORY_PRODUCT_FAILURE = 'CREATE_INVENTORY_PRODUCT_FAILURE';

export const GET_NOTIFICATION_COUNT_REQUEST = 'GET_NOTIFICATION_COUNT_REQUEST';
export const GET_NOTIFICATION_COUNT_SUCCESS = 'GET_NOTIFICATION_COUNT_SUCCESS';
export const GET_NOTIFICATION_COUNT_FAILURE = 'GET_NOTIFICATION_COUNT_FAILURE';

// Add these constants
export const GET_REPORTS_REQUEST = 'GET_REPORTS_REQUEST';
export const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS';
export const GET_REPORTS_FAILURE = 'GET_REPORTS_FAILURE';

export const GET_SELLER_DROPDOWN_REQUEST = 'GET_SELLER_DROPDOWN_REQUEST';
export const GET_SELLER_DROPDOWN_SUCCESS = 'GET_SELLER_DROPDOWN_SUCCESS';
export const GET_SELLER_DROPDOWN_FAILURE = 'GET_SELLER_DROPDOWN_FAILURE';

export const GET_STORE_DETAILS_REQUEST = 'GET_STORE_DETAILS_REQUEST';
export const GET_STORE_DETAILS_SUCCESS = 'GET_STORE_DETAILS_SUCCESS';
export const GET_STORE_DETAILS_FAILURE = 'GET_STORE_DETAILS_FAILURE';

export const GET_USER_STORE_DETAILS_REQUEST = 'GET_USER_STORE_DETAILS_REQUEST';
export const GET_USER_STORE_DETAILS_SUCCESS = 'GET_USER_STORE_DETAILS_SUCCESS';
export const GET_USER_STORE_DETAILS_FAILURE = 'GET_USER_STORE_DETAILS_FAILURE';

// Add these new action types for fulfillment types
export const GET_FULFILLMENT_TYPES_REQUEST = 'GET_FULFILLMENT_TYPES_REQUEST';
export const GET_FULFILLMENT_TYPES_SUCCESS = 'GET_FULFILLMENT_TYPES_SUCCESS';
export const GET_FULFILLMENT_TYPES_FAILURE = 'GET_FULFILLMENT_TYPES_FAILURE';

// Also update the AuthActionTypes interface in types.ts to include these new actions
interface GetFulfillmentTypesRequestAction {
  type: typeof GET_FULFILLMENT_TYPES_REQUEST;
}

interface GetFulfillmentTypesSuccessAction {
  type: typeof GET_FULFILLMENT_TYPES_SUCCESS;
  payload: any;
}

interface GetFulfillmentTypesFailureAction {
  type: typeof GET_FULFILLMENT_TYPES_FAILURE;
  payload: string;
}

// Add these to the AuthActionTypes union type
export type AuthActionTypes = 
  | GetFulfillmentTypesRequestAction
  | GetFulfillmentTypesSuccessAction
  | GetFulfillmentTypesFailureAction
  // ... other existing action types

