export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Add OTP verification action types
export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

// Add these action types
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

// Add these action types
export const GET_DASHBOARD_COUNTS_REQUEST = 'GET_DASHBOARD_COUNTS_REQUEST';
export const GET_DASHBOARD_COUNTS_SUCCESS = 'GET_DASHBOARD_COUNTS_SUCCESS';
export const GET_DASHBOARD_COUNTS_FAILURE = 'GET_DASHBOARD_COUNTS_FAILURE';

// Add these action types
export const GET_SELLER_COUNTS_REQUEST = 'GET_SELLER_COUNTS_REQUEST';
export const GET_SELLER_COUNTS_SUCCESS = 'GET_SELLER_COUNTS_SUCCESS';
export const GET_SELLER_COUNTS_FAILURE = 'GET_SELLER_COUNTS_FAILURE';

// Add these action types
export const GET_AFFILIATE_PARTNER_COUNTS_REQUEST = 'GET_AFFILIATE_PARTNER_COUNTS_REQUEST';
export const GET_AFFILIATE_PARTNER_COUNTS_SUCCESS = 'GET_AFFILIATE_PARTNER_COUNTS_SUCCESS';
export const GET_AFFILIATE_PARTNER_COUNTS_FAILURE = 'GET_AFFILIATE_PARTNER_COUNTS_FAILURE';

// Add these action types
export const GET_LOOKUP_CODES_REQUEST = 'GET_LOOKUP_CODES_REQUEST';
export const GET_LOOKUP_CODES_SUCCESS = 'GET_LOOKUP_CODES_SUCCESS';
export const GET_LOOKUP_CODES_FAILURE = 'GET_LOOKUP_CODES_FAILURE';

// Add these action types
export const UPDATE_USER_DETAILS_REQUEST = 'UPDATE_USER_DETAILS_REQUEST';
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_FAILURE = 'UPDATE_USER_DETAILS_FAILURE';

export const UPDATE_STORE_DETAILS_REQUEST = 'UPDATE_STORE_DETAILS_REQUEST';
export const UPDATE_STORE_DETAILS_SUCCESS = 'UPDATE_STORE_DETAILS_SUCCESS';
export const UPDATE_STORE_DETAILS_FAILURE = 'UPDATE_STORE_DETAILS_FAILURE';

export const FILE_UPLOAD_REQUEST = 'FILE_UPLOAD_REQUEST';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_FAILURE = 'FILE_UPLOAD_FAILURE';

export const UPDATE_BUSINESS_SETTINGS_REQUEST = 'UPDATE_BUSINESS_SETTINGS_REQUEST';
export const UPDATE_BUSINESS_SETTINGS_SUCCESS = 'UPDATE_BUSINESS_SETTINGS_SUCCESS';
export const UPDATE_BUSINESS_SETTINGS_FAILURE = 'UPDATE_BUSINESS_SETTINGS_FAILURE';

export const UPDATE_BANK_DETAILS_REQUEST = 'UPDATE_BANK_DETAILS_REQUEST';
export const UPDATE_BANK_DETAILS_SUCCESS = 'UPDATE_BANK_DETAILS_SUCCESS';
export const UPDATE_BANK_DETAILS_FAILURE = 'UPDATE_BANK_DETAILS_FAILURE';

export const GET_SELLER_DASHBOARD_COUNTS_REQUEST = 'GET_SELLER_DASHBOARD_COUNTS_REQUEST';
export const GET_SELLER_DASHBOARD_COUNTS_SUCCESS = 'GET_SELLER_DASHBOARD_COUNTS_SUCCESS';
export const GET_SELLER_DASHBOARD_COUNTS_FAILURE = 'GET_SELLER_DASHBOARD_COUNTS_FAILURE'; 